### PR TITLE
 feat(CI): Add Travis CI support

### PR DESCRIPTION
**Pull request by nickboldt**
replaces https://github.com/eclipse-che/che-machine-exec/pull/162

relates to https://github.com/eclipse/che/issues/19688

### CODE REVIEW

**Comment by nickboldt** [comment]
Note: this is not yet running in travis due to "Could not authorize build request" - see https://travis-ci.com/github/eclipse-che/che-machine-exec/requests?requestId=577440508

**Comment by Siddhesh-Ghadi** [comment]
Hi @nickboldt, looks like the job is not getting triggered due to token issue.

https://github.com/eclipse-che/che-machine-exec/pull/170/checks?check_run_id=2992405237
```bash
{
  "@type": "error",
  "error_type": "wrong_credentials",
  "error_message": "access denied"
}
```

Is [`secrets.TRAVIS_TOKEN`](https://github.com/eclipse-che/che-machine-exec/pull/170/files#diff-e4e76aa922e74c35eeb171d6a1e92ed66a940c383efd4a6012f589a4018ef8e4R54) variable set in Github Action?

**Comment by nickboldt** [comment]
> Is secrets.TRAVIS_TOKEN variable set in Github Action?

2 questions:

* what value shoud be in that token? can I generate one from https://travis-ci.com/github/eclipse-che/che-machine-exec/settings somewhere? 

* which action should be running the travis builds? is it in gh_actions_pr.yaml?
```
        curl -s -X POST \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        -H "Travis-API-Version: 3" \
        -H "Authorization: token ${{ secrets.TRAVIS_TOKEN }}" \
        -d "$body" \
        https://api.travis-ci.com/repo/eclipse-che%2Fche-machine-exec/requests
```

**Comment by Siddhesh-Ghadi** [comment]
> what value shoud be in that token? can I generate one from https://travis-ci.com/github/eclipse-che/che-machine-exec/settings somewhere?

Api token can be found under account preferences ( https://travis-ci.com/account/preferences )

api-token

> which action should be running the travis builds? is it in gh_actions_pr.yaml?

Yes. Travis build for PR check is triggered through `gh_actions_pr.yaml` and this will handle docker build as well as unit tests. For next build and release, `next-build.yaml` & `release.yml` files will trigger travis builds respectively.

**Comment by nickboldt** [comment]
I uploaded my exported token from https://travis-ci.com/account/preferences, then uploaded it as a secret called TRAVIS_TOKEN to eclipse-che/che-machine-exec ... but still failing. 

Also tried to re-trigger this PR's action to trigger the travis process... 

https://github.com/eclipse-che/che-machine-exec/runs/3019403781?check_suite_focus=true 

... but while the action shows succcess... over at https://travis-ci.com/github/eclipse-che/che-machine-exec/requests I'm seeing the same error:

image

**Comment by nickboldt** [comment]
Latest failures "Build config did not create any jobs" appear to be releated to https://github.com/travis-ci/travis-ci/issues/8536

**Comment by Siddhesh-Ghadi** [comment]
Hi @nickboldt, travis jobs will not be triggered until the jobs present in `.travis.yml` file are committed into the repo. It's kind of a limitation as we are using api calls to trigger travis jobs.

https://github.com/eclipse-che/che-machine-exec/pull/162#issuecomment-866897590
> PR check limitation on triggering PR-check jobs on Travis via API:
    - The Travis API token will be available to PRs raised by users with write access to that particular repo.
    - Changes made to .travis.yml file in PRs will not be validated in PR check Travis jobs until the changes are committed into the repo.

**Comment by nickboldt** [comment]
Uploaded 4 secrets to https://travis-ci.com/github/eclipse-che/che-machine-exec/settings

image

But I see that unlike the PR for theia, this one embeds the secrets directly (and uses different variable names):

image

**Comment by Prabhav-Thali** [comment]
Hi @nickboldt,

we had kept only 4 secrets in PR #162 (naming convention was followed as per GH actions secrets)i.e. 
```
DOCKER_PASSWORD
DOCKER_USERNAME
QUAY_PASSWORD
QUAY_USERNAME
```


Below variables are not required currently as Travis is experimental 
`GITHUB_TOKEN` - as execution of make-release.sh will happen only in GH action as it contains git operations.
`MATTERMOST_WEBHOOK_URL` - Not implemented in Travis for now.

**Comment by nickboldt** [comment]
Travis seems to think that machine-exec is a rake build... 

https://travis-ci.com/github/eclipse-che/che-machine-exec/builds/235580715

**Review by benoitf — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by benoitf** [comment]
@nickboldt I think it's because there is no .travis.yaml file yet ?

**Comment by benoitf** [comment]
the travis output shows that it's trying to execute it in the 'main' branch

**Comment by Prabhav-Thali** [comment]
Hi @nickboldt,
In case of PR check, As @Siddhesh-Ghadi has mentioned [here](https://github.com/eclipse-che/che-machine-exec/pull/170#issuecomment-876443046) about having limitations as we trigger PR check using API. Once changes are merged it will consider travis.yml from main branch and create jobs on Travis CI.

**Comment by Prabhav-Thali** [comment]
**Changes required in few files:**

- We will have to append one more condition [here](https://github.com/eclipse-che/che-machine-exec/blob/8b1554e0cfcb4025cd0cff0cf323827d3cfc0221/.travis.yml#L104) (`AND env(PR_NUMBER) IS blank`). Also same needs to be appended on all next build jobs if condition. This helps to restrict jobs only to next build as we are using API to trigger PR check as well.

- And as suggested [here](https://github.com/eclipse-che/che-theia/pull/1127#discussion_r664605178), we need to add eval before [this ](https://github.com/eclipse-che/che-machine-exec/blob/8b1554e0cfcb4025cd0cff0cf323827d3cfc0221/.travis/publish_multiarch.sh#L29)as enclosing AMEND in quotes leads to invalid reference format error. On every `docker manifest create` command, we will require eval. (Ref: .ci/travis/publish_multiarch.sh in https://github.com/eclipse-che/che-theia/pull/1127/files).

- Also, While testing we had observed that all the scripts which are used i.e.  .travis/build_image.sh and .travis/publish_multiarch.sh are required to be made executable otherwise permission denied error is seen in Travis build.

- Currently, as we will be executing jobs for PR check only. It will work fine as images wont be pushed. But in case of next and release build jobs, tags will collide with those pushed from GH actions as TRAVIS_TAG is removed in this [commit](https://github.com/eclipse-che/che-machine-exec/pull/170/commits/8b1554e0cfcb4025cd0cff0cf323827d3cfc0221). We might have to add it back or handle "-travis" for next and release build jobs as it was implemented in Che-theia [PR](https://github.com/eclipse-che/che-theia/pull/1127).

**Comment by nickboldt** [comment]
I've merged #170, so we can close this

**Pull request closed without merging**
